name: Salesforce DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Pipeline Check
        run: |
          echo "Salesforce DevSecOps pipeline is running successfully"
